// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.18.1
// source: msg/route.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Echo_MSGID int32

const (
	Echo_INVALID_MSGID Echo_MSGID = 0
	Echo_ID            Echo_MSGID = 99
)

// Enum value maps for Echo_MSGID.
var (
	Echo_MSGID_name = map[int32]string{
		0:  "INVALID_MSGID",
		99: "ID",
	}
	Echo_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            99,
	}
)

func (x Echo_MSGID) Enum() *Echo_MSGID {
	p := new(Echo_MSGID)
	*p = x
	return p
}

func (x Echo_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Echo_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[0].Descriptor()
}

func (Echo_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[0]
}

func (x Echo_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Echo_MSGID.Descriptor instead.
func (Echo_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{7, 0}
}

type EchoRequest_MSGID int32

const (
	EchoRequest_INVALID_MSGID EchoRequest_MSGID = 0
	EchoRequest_ID            EchoRequest_MSGID = 104
)

// Enum value maps for EchoRequest_MSGID.
var (
	EchoRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		104: "ID",
	}
	EchoRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            104,
	}
)

func (x EchoRequest_MSGID) Enum() *EchoRequest_MSGID {
	p := new(EchoRequest_MSGID)
	*p = x
	return p
}

func (x EchoRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[1].Descriptor()
}

func (EchoRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[1]
}

func (x EchoRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoRequest_MSGID.Descriptor instead.
func (EchoRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{8, 0}
}

type EchoResponse_MSGID int32

const (
	EchoResponse_INVALID_MSGID EchoResponse_MSGID = 0
	EchoResponse_ID            EchoResponse_MSGID = 105
)

// Enum value maps for EchoResponse_MSGID.
var (
	EchoResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		105: "ID",
	}
	EchoResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            105,
	}
)

func (x EchoResponse_MSGID) Enum() *EchoResponse_MSGID {
	p := new(EchoResponse_MSGID)
	*p = x
	return p
}

func (x EchoResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EchoResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[2].Descriptor()
}

func (EchoResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[2]
}

func (x EchoResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EchoResponse_MSGID.Descriptor instead.
func (EchoResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{9, 0}
}

type GroupBroadcastRequest_MSGID int32

const (
	GroupBroadcastRequest_INVALID_MSGID GroupBroadcastRequest_MSGID = 0
	GroupBroadcastRequest_ID            GroupBroadcastRequest_MSGID = 106
)

// Enum value maps for GroupBroadcastRequest_MSGID.
var (
	GroupBroadcastRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		106: "ID",
	}
	GroupBroadcastRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            106,
	}
)

func (x GroupBroadcastRequest_MSGID) Enum() *GroupBroadcastRequest_MSGID {
	p := new(GroupBroadcastRequest_MSGID)
	*p = x
	return p
}

func (x GroupBroadcastRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupBroadcastRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[3].Descriptor()
}

func (GroupBroadcastRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[3]
}

func (x GroupBroadcastRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupBroadcastRequest_MSGID.Descriptor instead.
func (GroupBroadcastRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{10, 0}
}

type GroupBroadcastResponse_MSGID int32

const (
	GroupBroadcastResponse_INVALID_MSGID GroupBroadcastResponse_MSGID = 0
	GroupBroadcastResponse_ID            GroupBroadcastResponse_MSGID = 107
)

// Enum value maps for GroupBroadcastResponse_MSGID.
var (
	GroupBroadcastResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		107: "ID",
	}
	GroupBroadcastResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            107,
	}
)

func (x GroupBroadcastResponse_MSGID) Enum() *GroupBroadcastResponse_MSGID {
	p := new(GroupBroadcastResponse_MSGID)
	*p = x
	return p
}

func (x GroupBroadcastResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupBroadcastResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[4].Descriptor()
}

func (GroupBroadcastResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[4]
}

func (x GroupBroadcastResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupBroadcastResponse_MSGID.Descriptor instead.
func (GroupBroadcastResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{11, 0}
}

type JoinGroupRequest_MSGID int32

const (
	JoinGroupRequest_INVALID_MSGID JoinGroupRequest_MSGID = 0
	JoinGroupRequest_ID            JoinGroupRequest_MSGID = 108
)

// Enum value maps for JoinGroupRequest_MSGID.
var (
	JoinGroupRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		108: "ID",
	}
	JoinGroupRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            108,
	}
)

func (x JoinGroupRequest_MSGID) Enum() *JoinGroupRequest_MSGID {
	p := new(JoinGroupRequest_MSGID)
	*p = x
	return p
}

func (x JoinGroupRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinGroupRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[5].Descriptor()
}

func (JoinGroupRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[5]
}

func (x JoinGroupRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinGroupRequest_MSGID.Descriptor instead.
func (JoinGroupRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{12, 0}
}

type JoinGroupResponse_MSGID int32

const (
	JoinGroupResponse_INVALID_MSGID JoinGroupResponse_MSGID = 0
	JoinGroupResponse_ID            JoinGroupResponse_MSGID = 109
)

// Enum value maps for JoinGroupResponse_MSGID.
var (
	JoinGroupResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		109: "ID",
	}
	JoinGroupResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            109,
	}
)

func (x JoinGroupResponse_MSGID) Enum() *JoinGroupResponse_MSGID {
	p := new(JoinGroupResponse_MSGID)
	*p = x
	return p
}

func (x JoinGroupResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinGroupResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[6].Descriptor()
}

func (JoinGroupResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[6]
}

func (x JoinGroupResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinGroupResponse_MSGID.Descriptor instead.
func (JoinGroupResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{13, 0}
}

type ListGroupRequest_MSGID int32

const (
	ListGroupRequest_INVALID_MSGID ListGroupRequest_MSGID = 0
	ListGroupRequest_ID            ListGroupRequest_MSGID = 110
)

// Enum value maps for ListGroupRequest_MSGID.
var (
	ListGroupRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		110: "ID",
	}
	ListGroupRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            110,
	}
)

func (x ListGroupRequest_MSGID) Enum() *ListGroupRequest_MSGID {
	p := new(ListGroupRequest_MSGID)
	*p = x
	return p
}

func (x ListGroupRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListGroupRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[7].Descriptor()
}

func (ListGroupRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[7]
}

func (x ListGroupRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListGroupRequest_MSGID.Descriptor instead.
func (ListGroupRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{15, 0}
}

type ListGroupResponse_MSGID int32

const (
	ListGroupResponse_INVALID_MSGID ListGroupResponse_MSGID = 0
	ListGroupResponse_ID            ListGroupResponse_MSGID = 111
)

// Enum value maps for ListGroupResponse_MSGID.
var (
	ListGroupResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		111: "ID",
	}
	ListGroupResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            111,
	}
)

func (x ListGroupResponse_MSGID) Enum() *ListGroupResponse_MSGID {
	p := new(ListGroupResponse_MSGID)
	*p = x
	return p
}

func (x ListGroupResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListGroupResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[8].Descriptor()
}

func (ListGroupResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[8]
}

func (x ListGroupResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListGroupResponse_MSGID.Descriptor instead.
func (ListGroupResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{16, 0}
}

type CreateGroupRequest_MSGID int32

const (
	CreateGroupRequest_INVALID_MSGID CreateGroupRequest_MSGID = 0
	CreateGroupRequest_ID            CreateGroupRequest_MSGID = 112
)

// Enum value maps for CreateGroupRequest_MSGID.
var (
	CreateGroupRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		112: "ID",
	}
	CreateGroupRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            112,
	}
)

func (x CreateGroupRequest_MSGID) Enum() *CreateGroupRequest_MSGID {
	p := new(CreateGroupRequest_MSGID)
	*p = x
	return p
}

func (x CreateGroupRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateGroupRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[9].Descriptor()
}

func (CreateGroupRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[9]
}

func (x CreateGroupRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateGroupRequest_MSGID.Descriptor instead.
func (CreateGroupRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{17, 0}
}

type CreateGroupResponse_MSGID int32

const (
	CreateGroupResponse_INVALID_MSGID CreateGroupResponse_MSGID = 0
	CreateGroupResponse_ID            CreateGroupResponse_MSGID = 113
)

// Enum value maps for CreateGroupResponse_MSGID.
var (
	CreateGroupResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		113: "ID",
	}
	CreateGroupResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            113,
	}
)

func (x CreateGroupResponse_MSGID) Enum() *CreateGroupResponse_MSGID {
	p := new(CreateGroupResponse_MSGID)
	*p = x
	return p
}

func (x CreateGroupResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateGroupResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[10].Descriptor()
}

func (CreateGroupResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[10]
}

func (x CreateGroupResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateGroupResponse_MSGID.Descriptor instead.
func (CreateGroupResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{18, 0}
}

type DeleteGroupRequest_MSGID int32

const (
	DeleteGroupRequest_INVALID_MSGID DeleteGroupRequest_MSGID = 0
	DeleteGroupRequest_ID            DeleteGroupRequest_MSGID = 114
)

// Enum value maps for DeleteGroupRequest_MSGID.
var (
	DeleteGroupRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		114: "ID",
	}
	DeleteGroupRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            114,
	}
)

func (x DeleteGroupRequest_MSGID) Enum() *DeleteGroupRequest_MSGID {
	p := new(DeleteGroupRequest_MSGID)
	*p = x
	return p
}

func (x DeleteGroupRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteGroupRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[11].Descriptor()
}

func (DeleteGroupRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[11]
}

func (x DeleteGroupRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteGroupRequest_MSGID.Descriptor instead.
func (DeleteGroupRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{19, 0}
}

type DeleteGroupResponse_MSGID int32

const (
	DeleteGroupResponse_INVALID_MSGID DeleteGroupResponse_MSGID = 0
	DeleteGroupResponse_ID            DeleteGroupResponse_MSGID = 115
)

// Enum value maps for DeleteGroupResponse_MSGID.
var (
	DeleteGroupResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		115: "ID",
	}
	DeleteGroupResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            115,
	}
)

func (x DeleteGroupResponse_MSGID) Enum() *DeleteGroupResponse_MSGID {
	p := new(DeleteGroupResponse_MSGID)
	*p = x
	return p
}

func (x DeleteGroupResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteGroupResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[12].Descriptor()
}

func (DeleteGroupResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[12]
}

func (x DeleteGroupResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteGroupResponse_MSGID.Descriptor instead.
func (DeleteGroupResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{20, 0}
}

type PutInGroupRequest_MSGID int32

const (
	PutInGroupRequest_INVALID_MSGID PutInGroupRequest_MSGID = 0
	PutInGroupRequest_ID            PutInGroupRequest_MSGID = 116
)

// Enum value maps for PutInGroupRequest_MSGID.
var (
	PutInGroupRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		116: "ID",
	}
	PutInGroupRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            116,
	}
)

func (x PutInGroupRequest_MSGID) Enum() *PutInGroupRequest_MSGID {
	p := new(PutInGroupRequest_MSGID)
	*p = x
	return p
}

func (x PutInGroupRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutInGroupRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[13].Descriptor()
}

func (PutInGroupRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[13]
}

func (x PutInGroupRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutInGroupRequest_MSGID.Descriptor instead.
func (PutInGroupRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{21, 0}
}

type PutInGroupResponse_MSGID int32

const (
	PutInGroupResponse_INVALID_MSGID PutInGroupResponse_MSGID = 0
	PutInGroupResponse_ID            PutInGroupResponse_MSGID = 117
)

// Enum value maps for PutInGroupResponse_MSGID.
var (
	PutInGroupResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		117: "ID",
	}
	PutInGroupResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            117,
	}
)

func (x PutInGroupResponse_MSGID) Enum() *PutInGroupResponse_MSGID {
	p := new(PutInGroupResponse_MSGID)
	*p = x
	return p
}

func (x PutInGroupResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutInGroupResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[14].Descriptor()
}

func (PutInGroupResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[14]
}

func (x PutInGroupResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutInGroupResponse_MSGID.Descriptor instead.
func (PutInGroupResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{22, 0}
}

type PutInGroupResponse_ErrCode int32

const (
	PutInGroupResponse_ok              PutInGroupResponse_ErrCode = 0
	PutInGroupResponse_unkown_err      PutInGroupResponse_ErrCode = 1
	PutInGroupResponse_group_not_found PutInGroupResponse_ErrCode = 2
)

// Enum value maps for PutInGroupResponse_ErrCode.
var (
	PutInGroupResponse_ErrCode_name = map[int32]string{
		0: "ok",
		1: "unkown_err",
		2: "group_not_found",
	}
	PutInGroupResponse_ErrCode_value = map[string]int32{
		"ok":              0,
		"unkown_err":      1,
		"group_not_found": 2,
	}
)

func (x PutInGroupResponse_ErrCode) Enum() *PutInGroupResponse_ErrCode {
	p := new(PutInGroupResponse_ErrCode)
	*p = x
	return p
}

func (x PutInGroupResponse_ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PutInGroupResponse_ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[15].Descriptor()
}

func (PutInGroupResponse_ErrCode) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[15]
}

func (x PutInGroupResponse_ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PutInGroupResponse_ErrCode.Descriptor instead.
func (PutInGroupResponse_ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{22, 1}
}

type ListGroupSessionRequest_MSGID int32

const (
	ListGroupSessionRequest_INVALID_MSGID ListGroupSessionRequest_MSGID = 0
	ListGroupSessionRequest_ID            ListGroupSessionRequest_MSGID = 118
)

// Enum value maps for ListGroupSessionRequest_MSGID.
var (
	ListGroupSessionRequest_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		118: "ID",
	}
	ListGroupSessionRequest_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            118,
	}
)

func (x ListGroupSessionRequest_MSGID) Enum() *ListGroupSessionRequest_MSGID {
	p := new(ListGroupSessionRequest_MSGID)
	*p = x
	return p
}

func (x ListGroupSessionRequest_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListGroupSessionRequest_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[16].Descriptor()
}

func (ListGroupSessionRequest_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[16]
}

func (x ListGroupSessionRequest_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListGroupSessionRequest_MSGID.Descriptor instead.
func (ListGroupSessionRequest_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{23, 0}
}

type ListGroupSessionResponse_MSGID int32

const (
	ListGroupSessionResponse_INVALID_MSGID ListGroupSessionResponse_MSGID = 0
	ListGroupSessionResponse_ID            ListGroupSessionResponse_MSGID = 119
)

// Enum value maps for ListGroupSessionResponse_MSGID.
var (
	ListGroupSessionResponse_MSGID_name = map[int32]string{
		0:   "INVALID_MSGID",
		119: "ID",
	}
	ListGroupSessionResponse_MSGID_value = map[string]int32{
		"INVALID_MSGID": 0,
		"ID":            119,
	}
)

func (x ListGroupSessionResponse_MSGID) Enum() *ListGroupSessionResponse_MSGID {
	p := new(ListGroupSessionResponse_MSGID)
	*p = x
	return p
}

func (x ListGroupSessionResponse_MSGID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListGroupSessionResponse_MSGID) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_route_proto_enumTypes[17].Descriptor()
}

func (ListGroupSessionResponse_MSGID) Type() protoreflect.EnumType {
	return &file_msg_route_proto_enumTypes[17]
}

func (x ListGroupSessionResponse_MSGID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListGroupSessionResponse_MSGID.Descriptor instead.
func (ListGroupSessionResponse_MSGID) EnumDescriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{24, 0}
}

type MsgSubType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgSubType) Reset() {
	*x = MsgSubType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSubType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubType) ProtoMessage() {}

func (x *MsgSubType) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubType.ProtoReflect.Descriptor instead.
func (*MsgSubType) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{0}
}

type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgtype uint32 `protobuf:"varint,1,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Msgname string `protobuf:"bytes,2,opt,name=msgname,proto3" json:"msgname,omitempty"`
	Seqid   uint32 `protobuf:"varint,3,opt,name=seqid,proto3" json:"seqid,omitempty"`
	Uid     uint64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{1}
}

func (x *Head) GetMsgtype() uint32 {
	if x != nil {
		return x.Msgtype
	}
	return 0
}

func (x *Head) GetMsgname() string {
	if x != nil {
		return x.Msgname
	}
	return ""
}

func (x *Head) GetSeqid() uint32 {
	if x != nil {
		return x.Seqid
	}
	return 0
}

func (x *Head) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type OSInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch    string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{2}
}

func (x *OSInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type NetworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DriverInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{4}
}

func (x *DriverInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ClientEnvInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Osinfo  *OSInfo      `protobuf:"bytes,1,opt,name=osinfo,proto3" json:"osinfo,omitempty"`
	Network *NetworkInfo `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *ClientEnvInfo) Reset() {
	*x = ClientEnvInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientEnvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvInfo) ProtoMessage() {}

func (x *ClientEnvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvInfo.ProtoReflect.Descriptor instead.
func (*ClientEnvInfo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{5}
}

func (x *ClientEnvInfo) GetOsinfo() *OSInfo {
	if x != nil {
		return x.Osinfo
	}
	return nil
}

func (x *ClientEnvInfo) GetNetwork() *NetworkInfo {
	if x != nil {
		return x.Network
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Uname  string   `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Role   string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Groups []string `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetUname() string {
	if x != nil {
		return x.Uname
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Echo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Echo) Reset() {
	*x = Echo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Echo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Echo) ProtoMessage() {}

func (x *Echo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Echo.ProtoReflect.Descriptor instead.
func (*Echo) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{7}
}

func (x *Echo) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{8}
}

func (x *EchoRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{9}
}

func (x *EchoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GroupBroadcastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group   string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Msgid   uint32 `protobuf:"varint,2,opt,name=msgid,proto3" json:"msgid,omitempty"`
	Msgdata []byte `protobuf:"bytes,3,opt,name=msgdata,proto3" json:"msgdata,omitempty"`
}

func (x *GroupBroadcastRequest) Reset() {
	*x = GroupBroadcastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupBroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBroadcastRequest) ProtoMessage() {}

func (x *GroupBroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBroadcastRequest.ProtoReflect.Descriptor instead.
func (*GroupBroadcastRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{10}
}

func (x *GroupBroadcastRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupBroadcastRequest) GetMsgid() uint32 {
	if x != nil {
		return x.Msgid
	}
	return 0
}

func (x *GroupBroadcastRequest) GetMsgdata() []byte {
	if x != nil {
		return x.Msgdata
	}
	return nil
}

type GroupBroadcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecvCount uint32 `protobuf:"varint,1,opt,name=recv_count,json=recvCount,proto3" json:"recv_count,omitempty"`
}

func (x *GroupBroadcastResponse) Reset() {
	*x = GroupBroadcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupBroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBroadcastResponse) ProtoMessage() {}

func (x *GroupBroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBroadcastResponse.ProtoReflect.Descriptor instead.
func (*GroupBroadcastResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{11}
}

func (x *GroupBroadcastResponse) GetRecvCount() uint32 {
	if x != nil {
		return x.RecvCount
	}
	return 0
}

type JoinGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{12}
}

func (x *JoinGroupRequest) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type JoinGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{13}
}

func (x *JoinGroupResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartAt uint32 `protobuf:"varint,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt   uint32 `protobuf:"varint,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{14}
}

func (x *Page) GetStartAt() uint32 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *Page) GetEndAt() uint32 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type ListGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page *Page `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListGroupRequest) Reset() {
	*x = ListGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupRequest) ProtoMessage() {}

func (x *ListGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupRequest.ProtoReflect.Descriptor instead.
func (*ListGroupRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Total  uint32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListGroupResponse) Reset() {
	*x = ListGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupResponse) ProtoMessage() {}

func (x *ListGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupResponse.ProtoReflect.Descriptor instead.
func (*ListGroupResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Invite []uint32 `protobuf:"varint,2,rep,packed,name=invite,proto3" json:"invite,omitempty"`
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{17}
}

func (x *CreateGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CreateGroupRequest) GetInvite() []uint32 {
	if x != nil {
		return x.Invite
	}
	return nil
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{18}
}

func (x *CreateGroupResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteGroupResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type PutInGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Invite []uint32 `protobuf:"varint,2,rep,packed,name=invite,proto3" json:"invite,omitempty"`
}

func (x *PutInGroupRequest) Reset() {
	*x = PutInGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutInGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInGroupRequest) ProtoMessage() {}

func (x *PutInGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInGroupRequest.ProtoReflect.Descriptor instead.
func (*PutInGroupRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{21}
}

func (x *PutInGroupRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *PutInGroupRequest) GetInvite() []uint32 {
	if x != nil {
		return x.Invite
	}
	return nil
}

type PutInGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errcode PutInGroupResponse_ErrCode `protobuf:"varint,1,opt,name=errcode,proto3,enum=route.PutInGroupResponse_ErrCode" json:"errcode,omitempty"`
	Invite  []uint32                   `protobuf:"varint,2,rep,packed,name=invite,proto3" json:"invite,omitempty"`
}

func (x *PutInGroupResponse) Reset() {
	*x = PutInGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutInGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutInGroupResponse) ProtoMessage() {}

func (x *PutInGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutInGroupResponse.ProtoReflect.Descriptor instead.
func (*PutInGroupResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{22}
}

func (x *PutInGroupResponse) GetErrcode() PutInGroupResponse_ErrCode {
	if x != nil {
		return x.Errcode
	}
	return PutInGroupResponse_ok
}

func (x *PutInGroupResponse) GetInvite() []uint32 {
	if x != nil {
		return x.Invite
	}
	return nil
}

type ListGroupSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Page  *Page  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListGroupSessionRequest) Reset() {
	*x = ListGroupSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupSessionRequest) ProtoMessage() {}

func (x *ListGroupSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupSessionRequest.ProtoReflect.Descriptor instead.
func (*ListGroupSessionRequest) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{23}
}

func (x *ListGroupSessionRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListGroupSessionRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListGroupSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uinfos []*UserInfo `protobuf:"bytes,1,rep,name=uinfos,proto3" json:"uinfos,omitempty"`
	Total  uint32      `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListGroupSessionResponse) Reset() {
	*x = ListGroupSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupSessionResponse) ProtoMessage() {}

func (x *ListGroupSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupSessionResponse.ProtoReflect.Descriptor instead.
func (*ListGroupSessionResponse) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{24}
}

func (x *ListGroupSessionResponse) GetUinfos() []*UserInfo {
	if x != nil {
		return x.Uinfos
	}
	return nil
}

func (x *ListGroupSessionResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// events
type EventSessionStatChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventSessionStatChange) Reset() {
	*x = EventSessionStatChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_route_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSessionStatChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSessionStatChange) ProtoMessage() {}

func (x *EventSessionStatChange) ProtoReflect() protoreflect.Message {
	mi := &file_msg_route_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSessionStatChange.ProtoReflect.Descriptor instead.
func (*EventSessionStatChange) Descriptor() ([]byte, []int) {
	return file_msg_route_proto_rawDescGZIP(), []int{25}
}

var File_msg_route_proto protoreflect.FileDescriptor

var file_msg_route_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x73, 0x67, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x53,
	0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x22, 0x62, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x73, 0x65, 0x71, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x06, 0x4f, 0x53,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x22, 0x21, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0a, 0x44, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x64, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45,
	0x6e, 0x76, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x73, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x4f,
	0x53, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x6f, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a,
	0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x5e, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x3e, 0x0a, 0x04, 0x45,
	0x63, 0x68, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x63, 0x22, 0x43, 0x0a, 0x0b, 0x45,
	0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x05,
	0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x68,
	0x22, 0x44, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x49, 0x44, 0x10, 0x69, 0x22, 0x81, 0x01, 0x0a, 0x15, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x73, 0x67, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x6a, 0x22, 0x5b, 0x0a, 0x16, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x63, 0x76, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x6b, 0x22, 0x4e, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x6c, 0x22, 0x4f, 0x0a, 0x11, 0x4a, 0x6f, 0x69, 0x6e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a,
	0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x6d, 0x22, 0x38, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x22, 0x57, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x6e, 0x22, 0x65, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x22,
	0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44,
	0x10, 0x6f, 0x22, 0x66, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12,
	0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x70, 0x22, 0x4f, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x71, 0x22, 0x4e, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44,
	0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x72, 0x22, 0x4f, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49,
	0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x73, 0x22, 0x65, 0x0a, 0x11,
	0x50, 0x75, 0x74, 0x49, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x22,
	0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49,
	0x44, 0x10, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x72,
	0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x49, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07,
	0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x22,
	0x22, 0x0a, 0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49,
	0x44, 0x10, 0x75, 0x22, 0x36, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06,
	0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x75, 0x6e, 0x6b, 0x6f, 0x77, 0x6e,
	0x5f, 0x65, 0x72, 0x72, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x22, 0x74, 0x0a, 0x17, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1f, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a,
	0x05, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0x76, 0x22, 0x7d, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x75, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x75, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x05,
	0x4d, 0x53, 0x47, 0x49, 0x44, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x4d, 0x53, 0x47, 0x49, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x77,
	0x22, 0x18, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x6d,
	0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_route_proto_rawDescOnce sync.Once
	file_msg_route_proto_rawDescData = file_msg_route_proto_rawDesc
)

func file_msg_route_proto_rawDescGZIP() []byte {
	file_msg_route_proto_rawDescOnce.Do(func() {
		file_msg_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_route_proto_rawDescData)
	})
	return file_msg_route_proto_rawDescData
}

var file_msg_route_proto_enumTypes = make([]protoimpl.EnumInfo, 18)
var file_msg_route_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_msg_route_proto_goTypes = []interface{}{
	(Echo_MSGID)(0),                     // 0: route.Echo.MSGID
	(EchoRequest_MSGID)(0),              // 1: route.EchoRequest.MSGID
	(EchoResponse_MSGID)(0),             // 2: route.EchoResponse.MSGID
	(GroupBroadcastRequest_MSGID)(0),    // 3: route.GroupBroadcastRequest.MSGID
	(GroupBroadcastResponse_MSGID)(0),   // 4: route.GroupBroadcastResponse.MSGID
	(JoinGroupRequest_MSGID)(0),         // 5: route.JoinGroupRequest.MSGID
	(JoinGroupResponse_MSGID)(0),        // 6: route.JoinGroupResponse.MSGID
	(ListGroupRequest_MSGID)(0),         // 7: route.ListGroupRequest.MSGID
	(ListGroupResponse_MSGID)(0),        // 8: route.ListGroupResponse.MSGID
	(CreateGroupRequest_MSGID)(0),       // 9: route.CreateGroupRequest.MSGID
	(CreateGroupResponse_MSGID)(0),      // 10: route.CreateGroupResponse.MSGID
	(DeleteGroupRequest_MSGID)(0),       // 11: route.DeleteGroupRequest.MSGID
	(DeleteGroupResponse_MSGID)(0),      // 12: route.DeleteGroupResponse.MSGID
	(PutInGroupRequest_MSGID)(0),        // 13: route.PutInGroupRequest.MSGID
	(PutInGroupResponse_MSGID)(0),       // 14: route.PutInGroupResponse.MSGID
	(PutInGroupResponse_ErrCode)(0),     // 15: route.PutInGroupResponse.ErrCode
	(ListGroupSessionRequest_MSGID)(0),  // 16: route.ListGroupSessionRequest.MSGID
	(ListGroupSessionResponse_MSGID)(0), // 17: route.ListGroupSessionResponse.MSGID
	(*MsgSubType)(nil),                  // 18: route.MsgSubType
	(*Head)(nil),                        // 19: route.Head
	(*OSInfo)(nil),                      // 20: route.OSInfo
	(*NetworkInfo)(nil),                 // 21: route.NetworkInfo
	(*DriverInfo)(nil),                  // 22: route.DriverInfo
	(*ClientEnvInfo)(nil),               // 23: route.ClientEnvInfo
	(*UserInfo)(nil),                    // 24: route.UserInfo
	(*Echo)(nil),                        // 25: route.Echo
	(*EchoRequest)(nil),                 // 26: route.EchoRequest
	(*EchoResponse)(nil),                // 27: route.EchoResponse
	(*GroupBroadcastRequest)(nil),       // 28: route.GroupBroadcastRequest
	(*GroupBroadcastResponse)(nil),      // 29: route.GroupBroadcastResponse
	(*JoinGroupRequest)(nil),            // 30: route.JoinGroupRequest
	(*JoinGroupResponse)(nil),           // 31: route.JoinGroupResponse
	(*Page)(nil),                        // 32: route.Page
	(*ListGroupRequest)(nil),            // 33: route.ListGroupRequest
	(*ListGroupResponse)(nil),           // 34: route.ListGroupResponse
	(*CreateGroupRequest)(nil),          // 35: route.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 36: route.CreateGroupResponse
	(*DeleteGroupRequest)(nil),          // 37: route.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),         // 38: route.DeleteGroupResponse
	(*PutInGroupRequest)(nil),           // 39: route.PutInGroupRequest
	(*PutInGroupResponse)(nil),          // 40: route.PutInGroupResponse
	(*ListGroupSessionRequest)(nil),     // 41: route.ListGroupSessionRequest
	(*ListGroupSessionResponse)(nil),    // 42: route.ListGroupSessionResponse
	(*EventSessionStatChange)(nil),      // 43: route.EventSessionStatChange
}
var file_msg_route_proto_depIdxs = []int32{
	20, // 0: route.ClientEnvInfo.osinfo:type_name -> route.OSInfo
	21, // 1: route.ClientEnvInfo.network:type_name -> route.NetworkInfo
	32, // 2: route.ListGroupRequest.page:type_name -> route.Page
	15, // 3: route.PutInGroupResponse.errcode:type_name -> route.PutInGroupResponse.ErrCode
	32, // 4: route.ListGroupSessionRequest.page:type_name -> route.Page
	24, // 5: route.ListGroupSessionResponse.uinfos:type_name -> route.UserInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_msg_route_proto_init() }
func file_msg_route_proto_init() {
	if File_msg_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSubType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OSInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientEnvInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Echo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupBroadcastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupBroadcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutInGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutInGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_route_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSessionStatChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_route_proto_rawDesc,
			NumEnums:      18,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_route_proto_goTypes,
		DependencyIndexes: file_msg_route_proto_depIdxs,
		EnumInfos:         file_msg_route_proto_enumTypes,
		MessageInfos:      file_msg_route_proto_msgTypes,
	}.Build()
	File_msg_route_proto = out.File
	file_msg_route_proto_rawDesc = nil
	file_msg_route_proto_goTypes = nil
	file_msg_route_proto_depIdxs = nil
}
